### ISSUE TITLE
Chromedriver issues

### ISSUE THREAD

**Issue by jasperan** [adriangoris/social-nukeit-python#1]
Here is the traceback:

jasper@jasper-xfg:~/github/facebook-nukeit-python$ sudo python facebook-nukeit.py 
https://mbasic.facebook.com//allactivity
Traceback (most recent call last):
  File "facebook-nukeit.py", line 152, in <module>
    main()
  File "facebook-nukeit.py", line 147, in main
    fbni = FacebookNukeIt(fb_username, fb_password)
  File "facebook-nukeit.py", line 35, in __init__
    self.driver = webdriver.Chrome(executable_path="/usr/local/bin/chromedriver", chrome_options=chrome_options)
  File "/home/jasper/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/jasper/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jasper/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jasper/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/jasper/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /u

**Comment by jasperan** [comment]
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

**Comment by adriangoris** [comment]
It appears you have an outdated chrome driver. 

https://github.com/adriangoris/facebook-nukeit-python

> If your version is not 2.42 do one of the following:
brew uninstall chromedriver
brew tap homebrew/cask
brew cask install chromedriver
chromedriver --version

**Comment by adriangoris** [comment]
This repo is not ready for public use. 
I recommend you use the facebook package individually: 

https://github.com/adriangoris/facebook-nukeit-python
